import Head from "next/head";
import Nav from "../sections/Nav";
import Footer from "../sections/Footer";
import Script from "next/script";
import Link from "next/link";

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>YTU Girişimcilik Kulübü</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
                {/* box icons */}
                <link
                    href="https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css"
                    rel="stylesheet"
                />
                <script
                    type="module"
                    src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.esm.js"
                ></script>
                <script
                    nomodule=""
                    src="https://unpkg.com/ionicons@5.1.2/dist/ionicons/ionicons.js"
                ></script>
                <link
                    href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css"
                    rel="stylesheet"
                />
            </Head>
            <Nav />
            <main className="l-main">
                <div>
                    <div>{children}</div>
                </div>
            </main>
            <Footer />
        </>
    );
};

export default Layout;
